"""add app_activated to user

Revision ID: 1e9a1620557c
Revises: f1a2b3c4d5e6
Create Date: 2026-08-19 13:07:22.672069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9a1620557c'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_activated', sa.Boolean(), nullable=False, server_default='1'))
    op.alter_column('users', 'app_activated', server_default=None)
    op.add_column('users', sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activated_at')
    op.drop_column('users', 'app_activated')
    # ### end Alembic commands ###
